apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-project-core.fullname" . }}-project
  labels:
    {{- include "otus-project-core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otus-project-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otus-project-core.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-project
          image: "{{ .Values.image.repository.project }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort.project }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.pgUsernameKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.pgPasswordKey }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
      volumes:
          - name: config
            configMap:
              name: {{ .Values.configMap.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-project-core.fullname" . }}-manifest
  labels:
    {{- include "otus-project-core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otus-project-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otus-project-core.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-manifest
          image: "{{ .Values.image.repository.manifest }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort.manifest }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.pgUsernameKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.pgPasswordKey }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configMap.name }}