apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-project-core.fullname" . }}-project
  labels:
    {{- include "otus-project-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort.project }}
      protocol: TCP
      name: http
  selector:
    {{- include "otus-project-core.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-project-core.fullname" . }}-manifest
  labels:
    {{- include "otus-project-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort.manifest }}
      protocol: TCP
      name: http
  selector:
    {{- include "otus-project-core.selectorLabels" . | nindent 4 }}